import { useState } from 'react'
import type { Task } from '../types'
import { uid } from '../store/seed'

type Comment = NonNullable<Task['comments']>[number]
type Attachment = NonNullable<Task['attachments']>[number]
export function CardExtras({ cover, onCover, comments, onComments, attachments, onAttachments }: { cover: string; onCover: (value: string) => void; comments: Comment[]; onComments: (value: Comment[]) => void; attachments: Attachment[]; onAttachments: (value: Attachment[]) => void }) {
  const [comment, setComment] = useState('')
  const [url, setUrl] = useState('')
  const [name, setName] = useState('')
  const [error, setError] = useState('')
  return <div className="card-extras"><section><h3>Cover</h3><div className="cover-swatches">{['', '#579dff', '#4bce97', '#f5cd47', '#f87168', '#9f8fef', '#60c6d2'].map(color => <button type="button" key={color} style={{ background: color || 'var(--canvas)' }} aria-label={color ? `Set cover ${color}` : 'Remove cover'} aria-pressed={cover === color} onClick={() => onCover(color)}>{!color ? 'None' : cover === color ? '✓' : ''}</button>)}</div></section><section><h3>Attachments <span>{attachments.length}</span></h3><p className="field-help">Add links to designs, documents, or project files.</p>{attachments.map(item => <div className="attachment-row" key={item.id}><a href={item.url} target="_blank" rel="noopener noreferrer">{item.name}</a><button type="button" className="icon-button" aria-label={`Remove ${item.name}`} onClick={() => onAttachments(attachments.filter(a => a.id !== item.id))}>×</button></div>)}<div className="form-grid"><label>Link name<input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Design document" /></label><label>URL<input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://…" /></label></div><button type="button" className="secondary-action" disabled={!url.trim()} onClick={() => { try { const link = new URL(url.trim()); if (!['https:', 'http:'].includes(link.protocol)) throw new Error(); onAttachments([...attachments, { id: uid(), name: name.trim() || link.hostname, url: link.href }]); setName(''); setUrl(''); setError('') } catch { setError('Enter a valid http or https URL.') } }}>Attach link</button>{error && <p className="form-error" role="alert">{error}</p>}</section><section><h3>Personal activity & comments</h3><textarea aria-label="New personal comment" placeholder="Write an update or decision…" value={comment} onChange={e => setComment(e.target.value)} rows={2} /><button type="button" className="secondary-action" disabled={!comment.trim()} onClick={() => { onComments([...comments, { id: uid(), text: comment.trim(), createdAt: new Date().toISOString() }]); setComment('') }}>Add comment</button>{[...comments].reverse().map(item => <div className="comment-row" key={item.id}><span className="comment-avatar">ME</span><div><strong>You <time>{new Date(item.createdAt).toLocaleString()}</time></strong><p>{item.text}</p></div><button type="button" className="icon-button" aria-label="Delete comment" onClick={() => onComments(comments.filter(c => c.id !== item.id))}>×</button></div>)}<p className="field-help">Save changes to keep added links and comments.</p></section></div>
}
